{% set data = load_setup_py_data() %}

package:
  name: compute-wps
  version: {{ data.get('version') }}

source:
  path: ./

build:
  build: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - django
    - django-cors-headers
    - djangorestframework
    - esgf-compute-api
    - jinja2
    - gunicorn
    - psycopg2
    - pyzmq
    - requests
    - prometheus_client
    - pyyaml
    - oauthlib
    - python-coreapi

test:
  imports:
    - compute_wps

about:
  home: https://github.com/ESGF/esgf-compute-wps
  summary: LLNL WPS Django Application
