development: true

traefik:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi

    limits:
      cpu: 500m
      memory: 512Mi

  dashboard:
      labels:
        traffic-type: development

  kubernetes:
    labelSelector: traffic-type=development-internal

persistence:
  dataClaimName: data-dev-pvc

  volumes:
    data-dev:
      storageClassName: slow
      capacity: 100Gi
      path: /p/cscratch/nimbus/wps-dev/data

wps:
  # Sets the wps container to development mode
  # development: true

  imagePullPolicy: Always

  nodeSelector:
    tier: backend

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  ingress:
    external:
      labels:
        traffic-type: development
    internal:
      labels:
        traffic-type: development-internal

  externalHost: 10.5.5.5

  prometheus:
    host: sdasda

  oauth:
    client: client
    secret: secret

  apiUsername: wps_api_user
  apiPassword: changeit

  adminEmail: test@test.hello

  email:
    host: dasda

celery:
  # Sets the celery container to development mode
  # development: true

  imagePullPolicy: Always

  nodeSelector:
    tier: backend

  backend:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

  prometheusUrl: https://fakepromserver.org

  # backend:
  #   Sets the celery backend container to development mode
  #   development: true

provisioner:
  # Sets provisioner container to development mode
  # development: true

  imagePullPolicy: Always

  nodeSelector:
    tier: backend

  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    request:
      cpu: 100m
      memory: 32Mi

  workers: 2

  lifetime: 240

kubeMonitor:
  # Sets kube-monitor container to development mode
  # development: true

  imagePullPolicy: Always

  nodeSelector:
    tier: backend

  namespace: development

  resources:
    limits:
      cpu: 1
      memory: 512Mi

    requests:
      cpu: 500m
      memory: 256Mi

nginx:
  imagePullPolicy: Always
    
  nodeSelector:
    tier: backend

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

  ingress:
    labels:
      traffic-type: development

thredds:
  nodeSelector:
    tier: backend

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi

  ingress:
    labels:
      traffic-type: development

postgresql:
  postgresqlPassword: abcd1234

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  persistence:
    enabled: false

  master:
    nodeSelector:
      tier: backend

redis:
  master:
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 2
        memory: 4Gi

    persistence:
      enabled: false

    nodeSelector:
      tier: backend
