prometheus:
  enabled: true

  alertmanager:
    enabled: true
    prefixURL: /prometheus-alert
    baseURL: /prometheus-alert

    ingress:
      enabled: true
      hosts:
      - /prometheus-alert

      extraLabels:
        traffic-type: development

    persistentVolume:
      enabled: false

  nodeExporter:
    image:
      tag: v0.18.0

  server:
    prefixURL: /prometheus
    baseURL: /prometheus

    ingress:
      enabled: true
      hosts:
      - /prometheus

      extraLabels:
        traffic-type: development

    persistentVolume:
      enabled: false

  pushgateway:
    enabled: false
