traefik:
  serviceType: NodePort

  debug:
    enabled: true

  resources:
    requests:
      cpu: 200m
      memory: 256Mi

    limits:
      cpu: 500m
      memory: 512Mi

  nodeSelector:
    kubernetes.io/hostname: nimbus16

  rbac:
    enabled: true

  ssl:
    enabled: true
    enforced: true
    tlsMinVersion: VersionTLS12
    cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
    generateTLS: true

  dashboard:
    enabled: true
    domain: ""
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
      labels:
        traffic-type: development

  kubernetes:
    labelSelector: traffic-type=development

  metrics:
    prometheus:
      enabled: true
      restrictAccess: true

  deployment:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
      
    hostPort:
      httpEnabled: true
      httpPort: 8000
      httpsEnabled: true
      httpsPort: 8443
