version: '2'
services:
  wps:
    image: jasonb87/cwt_wps:latest
    environment:
      - OAUTH_CLIENT
      - OAUTH_SECRET
      - WPS_INIT=1
      - CELERY_BROKER=redis://redis/0
      - CELERY_BACKEND=redis://redis/0
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    volumes:
      - /data
    networks:
      frontend:
      backend:
  postgres:
    image: postgres:9.6.2
    environment: 
      - POSTGRES_PASSWORD=1234
    networks:
      frontend:
  redis:
    image: redis:3.2.8
    networks:
      frontend:
  celery:
    image: jasonb87/cwt_celery:latest
    environment:
      - OAUTH_CLIENT
      - OAUTH_SECRET
      - CELERY_BROKER=redis://redis/0
      - CELERY_BACKEND=redis://redis/0
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes_from:
      - wps
    networks:
      frontend:
      backend:
  cdas:
    image: jasonb87/cwt_cdas2:latest
    expose:
      - "4356"
      - "4357"
    volumes_from:
      - wps
    networks:
      backend:
  thredds:
    image: jasonb87/cwt_thredds
    expose:
      - "8080"
    volumes_from:
      - wps
    networks:
      backend:

networks:
  frontend:
  backend:
