version: '2'
services:
  wps:
    image: jasonb87/esgf_wps:latest
    environment:
      - CELERY_BROKER=redis://redis/0
      - CELERY_BACKEND=redis://redis/0
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./../esgf-compute-api:/esgf-compute-api
    networks:
      frontend:
  postgres:
    image: postgres:9.6.2
    environment: 
      - POSTGRES_PASSWORD=1234
    networks:
      frontend:
  redis:
    image: redis:latest
    networks:
      frontend:
  celery:
    image: jasonb87/celery:latest
    environment:
      - WPS_NO_INIT=1
      - CELERY_BROKER=redis://redis/0
      - CELERY_BACKEND=redis://redis/0
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes_from:
      - wps
    command: sleep infinity
    networks:
      frontend:
      backend:
  cdas:
    image: jasonb87/cdas2:latest
    expose:
      - "4356"
      - "4357"
    networks:
      backend:

networks:
  frontend:
  backend:
