# Container versions

export COMPUTE_CELERY_VER='0.1.0'
export COMPUTE_KUBE_MONITOR_VER='0.1.0'
export COMPUTE_PROVISIONER_VER='0.1.0'
export COMPUTE_THREDDS_VER='4.6.10'
export COMPUTE_WEBAPP_VER='0.1.0'
export COMPUTE_WPS_VER='0.1.0'

# Library versions

export COMPUTE_API_VER='0.1.0'
export COMPUTE_KUBERNETES_VER='0.1.0'
export COMPUTE_PROV_VER='0.1.0'
export COMPUTE_SETTINGS_VER='0.1.0'
export COMPUTE_TASKS_VER='0.1.0'
export COMPUTE_WPS_VER='0.1.0'
