{% set data = load_setup_py_data() %}

package:
  name: compute-kubernetes
  version: {{ data.get('version') }}

source:
  path: ./

build:
  build: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - python-kubernetes=9.0.0
    - distributed=1.28.0
    - redis-py=3.2.1

test:
  imports:
    - compute_kubernetes
    - compute_kubernetes.cluster

about:
  home: https://github.com/ESGF/esgf-compute-wps
