package:
  name: compute-kubernetes
  version: {{ environ.get('APP_VERSION', 'devel') }}

source:
  path: ./

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python

  run:
    - python=3.6.7
    - python-kubernetes=9.0.0
    - distributed=1.28.0
    - pyaml=19.4.1

test:
  imports:
    - compute_kubernetes
    - compute_kubernetes.cluster
    - compute_kubernetes.cluster_manager

about:
  home: https://github.com/ESGF/esgf-compute-wps
