kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: celery-beat-deployment
  labels:
    app: wps
spec:
  selector:
    matchLabels:
      app: wps
  template:
    metadata:
      labels:
        app: wps
    spec:
      containers:
      - name: celery-beat
        image: jasonb87/cwt_celery:2.0.0
        command: ["-l", "info", "-B"]
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /data/public
          name: public-volume
        - mountPath: /data/cache
          name: cache-volume
      volumes:
      - name: config-volume
        configMap:
          name: django-config
      - name: public-volume
        hostPath:
          path: /opt/nfs/cwt/data/public
          type: DirectoryOrCreate
      - name: cache-volume
        hostPath:
          path: /opt/nfs/cwt/data/public
          type: DirectoryOrCreate
