kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: celery-beat-deployment
  labels:
    app: wps
spec:
  selector:
    matchLabels:
      app: wps
  template:
    metadata:
      labels:
        app: wps
    spec:
      containers:
      - name: celery-beat
        image: jasonb87/cwt_celery:latest
        command: ["-l", "info", "-B"]
