apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: celery-deployment
  labels:
    app: wps
spec:
  selector:
    matchLabels:
      app: wps
  template:
    metadata:
      labels:
        app: wps
    spec:
      containers:
      - name: celery
        image: jasonb87/cwt_celery:latest
