kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: celery-beat-deployment
  labels:
    app: wps
spec:
  selector:
    matchLabels:
      app: wps
  template:
    metadata:
      labels:
        app: wps
    spec:
      containers:
      - name: celery-beat
        image: jasonb87/cwt_celery:2.0.0
        command: ["-l", "info", "-B"]
        env:
        - name: WPS_HOST
          value: "192.168.39.170"
        - name: CELERY_BROKER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: celery_broker
        - name: CELERY_BACKEND
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: celery_backend
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: postgres_host
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: postgres_password
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /data/public
          name: public-volume
        - mountPath: /data/cache
          name: cache-volume
      volumes:
      - name: config-volume
        configMap:
          name: django-config
      - name: public-volume
        hostPath:
          path: /opt/nfs/cwt/data/public
          type: DirectoryOrCreate
      - name: cache-volume
        hostPath:
          path: /opt/nfs/cwt/data/public
          type: DirectoryOrCreate
