apiVersion: apps/v1
kind: Deployment
metadata:
  name: cog-deployment
  labels:
    app: cog
    environment: debug
spec:
  selector:
    matchLabels:
      app: cog
  template:
    metadata:
      labels:
        app: cog
    spec:
      containers:
      - name: cog
        image: jasonb87/cwt_cog:latest
        args: ["aims2.llnl.gov", "false", "true", "https://aims2.llnl.gov/wps/home/configure", "true"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /usr/local/cog/cog_install/static
          name: static-volume
      volumes:
      - name: static-volume
        hostPath:
          path: /opt/nfs/cwt/data/static
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: cog
spec:
  selector:
    app: cog
  ports:
  - protocol: TCP
    port: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cog-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend: 
          serviceName: cog
          servicePort: 8000
