apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: edas-deployment
  labels:
    app: edas
    component: edas
    group: edas
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      component: edas
  template:
    metadata:
      labels:
        component: edas
    spec:
      containers:
      - name: edas
        image: jasonb87/cwt_edas:latest
        resources:
          limits:
            cpu: "2"
            memory: "400Mi"
          requests:
            cpu: "1"
            memory: "200Mi"
        volumeMounts:
        - mountPath: /data/public
          name: public-volume
        - mountPath: /data/cache
          name: cache-volume
      volumes:
      - name: public-volume
        hostPath:
          path: /opt/nfs/cwt/data/public
          type: DirectoryOrCreate
      - name: cache-volume
        hostPath:
          path: /opt/nfs/cwt/data/cache
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: edas
  labels:
    app: edas
    component: edas
    group: edas
    environment: production
spec:
  selector:
    app: edas
  ports:
  - name: listen
    protocol: TCP
    port: 5670
  - name: send
    protocol: TCP
    port: 5671
