apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: edas-deployment
  labels:
    app: wps
spec:
  selector:
    matchLabels:
      app: wps
  template:
    metadata:
      labels:
        app: wps
    spec:
      containers:
      - name: edas
        image: jasonb87/cwt_edas:latest
---
apiVersion: v1
kind: Service
metadata:
  name: edas
spec:
  selector:
    app: wps
  ports:
  - name: listen
    protocol: TCP
    port: 5670
  - name: send
    protocol: TCP
    port: 5671
