apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: wps
spec:
  selector:
    matchLabels:
      app: wps
      component: redis
  template:
    metadata:
      labels:
        app: wps
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2.8
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: wps
    component: redis
  ports:
  - protocol: TCP
    port: 6379
