apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: thredds-deployment
  labels:
    app: wps
spec:
  selector:
    matchLabels:
      app: wps
  template:
    metadata:
      labels:
        app: wps
    spec:
      containers:
      - name: thredds
        image: jasonb87/cwt_thredds:latest
