defaultEntryPoints = ["http", "https"]

[entryPoints]
	[entryPoints.http]
	address = ":80"
		[entryPoints.http.redirect]
			entryPoint = "https"
	[entryPoints.https]
	address = ":443"
		[entryPoints.https.tls]
			[[entryPoints.https.tls.certificates]]
			CertFile = "/etc/ssl/tls.crt"
			KeyFile = "/etc/ssl/tls.key"
