apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-deployment
  labels:
    app: wps
spec:
  selector:
    matchLabels:
      app: wps
      component: traefik
  template:
    metadata:
      labels:
        app: wps
        component: traefik
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik
        args:
        - --api
        - --kubernetes
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ui
  labels:
    app: wps
    component: traefik-ui
spec:
  selector:
    app: wps
    component: traefik
  ports:
  - port: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /dashboard
        backend:
          serviceName: traefik-ui
          servicePort: 8080
