---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  labels:
    app: cwt
    component: traefik
    group: traefik
    environment: production
    environment: development
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: traefik-ingress-controller
  labels:
    app: cwt
    component: traefik
    group: traefik
    environment: production
    environment: development
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-controller
  labels:
    app: cwt
    component: traefik
    group: traefik
    environment: production
    environment: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-deployment
  labels:
    app: cwt
    component: traefik
    group: traefik
    environment: production
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      component: traefik
  template:
    metadata:
      labels:
        component: traefik
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: traefik-ingress-controller
      containers:
      - image: traefik
        name: traefik
        resources:
          limits:
            cpu: "1"
            memory: "400Mi"
          requests:
            cpu: "0.25"
            memory: "200Mi"
        args:
        - --api
        - --kubernetes
        - --configFile=/etc/config/traefik.toml
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        volumeMounts:
        - name: ssl-volume
          mountPath: /etc/ssl
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: ssl-volume
        secret:
          secretName: ssl-secret
      - name: config-volume
        configMap:
          name: traefik-config
