defaultEntryPoints = ["http", "https"]

[entryPoints]
	[entryPoints.http]
	address = ":80"
		[entryPoints.http.redirect]
			entryPoint = "https"
	[entryPoints.https]
	address = ":443"
		[entryPoints.https.tls]
		minVersion = "VersionTLS12"
		cipherSuites = [
			"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
			"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
			"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
			"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
			"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
			"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
			"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
			"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
			"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
			"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
			#"TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
			#"TLS_ECDHE_RSA_WITH_RC4_128_SHA",
			"TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
			"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
			"TLS_ECDHE_ECDSA_WITH_RC4_128_SHA",
			#"TLS_RSA_WITH_AES_256_GCM_SHA384",
			#"TLS_RSA_WITH_AES_128_GCM_SHA256",
			#"TLS_RSA_WITH_AES_128_CBC_SHA256",
			#"TLS_RSA_WITH_AES_256_CBC_SHA",
			#"TLS_RSA_WITH_AES_128_CBC_SHA",
			#"TLS_RSA_WITH_3DES_EDE_CBC_SHA",
			#"TLS_RSA_WITH_RC4_128_SHA"
		]	
			[[entryPoints.https.tls.certificates]]
			CertFile = "/etc/ssl/tls.crt"
			KeyFile = "/etc/ssl/tls.key"
