# Generated by Django 2.2.5 on 2019-09-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_wps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
