# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0004_unique_status_per_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='steps_completed',
        ),
        migrations.RemoveField(
            model_name='job',
            name='steps_total',
        ),
        migrations.AddField(
            model_name='output',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='wps.Job'),
        ),
    ]
