# Generated by Django 3.1.2 on 2020-10-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compute_wps', '0006_adds_keycloakuserclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='expired',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
