# Generated by Django 3.1.2 on 2020-10-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_wps', '0007_fix_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='extra',
        ),
        migrations.AddField(
            model_name='job',
            name='datainputs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
