# Generated by Django 3.1.2 on 2020-10-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compute_wps', '0008_remove_job_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='exception',
        ),
        migrations.RemoveField(
            model_name='status',
            name='output',
        ),
    ]
