# Generated by Django 3.1.2 on 2020-10-28 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute_wps', '0009_remove_job_output_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='compute_wps.process'),
            preserve_default=False,
        ),
    ]
