# Generated by Django 3.1.2 on 2020-10-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compute_wps', '0010_fix_null_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='backend',
        ),
    ]
