# Generated by Django 3.1.2 on 2020-10-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute_wps', '0012_remove_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compute_wps.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compute_wps.job'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'host', 'variable')},
        ),
    ]
