# Generated by Django 3.1.7 on 2021-03-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_wps', '0014_add_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='remote',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
