# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0017_store_openid_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='job',
            name='report',
        ),
        migrations.RemoveField(
            model_name='message',
            name='exception',
        ),
        migrations.AddField(
            model_name='job',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wps.Process'),
        ),
        migrations.AddField(
            model_name='status',
            name='exception',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='output',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
