# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0018_status_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra',
            field=models.TextField(null=True),
        ),
    ]
