# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0029_cache_size_conversion_byte_gigabyte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
