{% set data = load_setup_py_data() %}

package:
  name: compute-tasks
  version: {{ data.get('version') }}

source:
  path: ./

build:
  build: {{ environ.get('BUILD_NUM', 0) }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  entry_points:
    - compute-tasks-metrics = compute_tasks.metrics_:main
    - compute-tasks-backend = compute_tasks.backend:main

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - nomkl
    - cdms2
    - numpy<=1.17.5
    - esgf-compute-api
    - pyzmq
    - redis-py=3.2.0
    - requests
    - celery
    - prometheus_client
    - dask
    - dask-kubernetes
    - distributed
    - xarray
    - metpy
    - cftime=1.0.3.4 # Need 1.0.3.4 until next version of xarray
    - netcdf4
    - python-coreapi

test:
  imports:
    - compute_tasks
  source_files:
    - compute_tasks/tests
    - conftest.py 
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
    - myproxyclient
  commands:
    - pytest -vvv -m "not myproxyclient" --junit-xml=/testing/unittest.xml --cov=compute_tasks --cov-report=xml:/testing/coverage.xml

about:
  home: https://github.com/ESGF/esgf-compute-wps
  summary: LLNL WPS Django Application
