{% set data = load_setup_py_data() %}

package:
  name: compute-tasks
  version: {{ data.get('version') }}

source:
  path: ./

build:
  build: {{ environ.get('BUILD_NUM', 0) }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  entry_points:
    - compute-tasks-metrics = compute_tasks.metrics_:main
    - compute-tasks-backend = compute_tasks.backend:main

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - esgf-compute-api
    - pyzmq
    - redis-py
    - requests
    - celery
    - prometheus_client
    - dask
    - dask-kubernetes
    - distributed
    - xarray
    - metpy
    - cftime
    - netcdf4
    - python-coreapi
    - zarr
    - dask-gateway

test:
  imports:
    - compute_tasks

about:
  home: https://github.com/ESGF/esgf-compute-wps
  summary: LLNL WPS Django Application
