version: '3.2'
services:
  wps:
    image: jasonb87/cwt_wps:latest
    entrypoint: sleep infinity
    env_file:
      - ./common.env
    ports:
      - "8000:8000"
    volumes:
      - conf-volume:/var/www/compute
      - static-volume:/var/www/static
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      frontend:
      backend:
  postgres:
    image: postgres:9.6.2
    environment: 
      - POSTGRES_PASSWORD=1234
    volumes:
      - db-volume:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      frontend:
  redis:
    image: redis:3.2.8
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      frontend:
  celery:
    image: jasonb87/cwt_celery:latest
    env_file:
      - ./common.env
    volumes:
      - conf-volume:/var/www/compute
      - data-volume:/data/public
      - cache-volume:/data/cache
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '2.0'
    networks:
      frontend:
      backend:
  thredds:
    image: jasonb87/cwt_thredds:latest
    ports:
      - "8080:8080"
    volumes:
      - data-volume:/data/public
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      backend:
  edas:
    image: jasonb87/cwt_edas:latest
    expose:
      - "5670"
      - "5671"
    volumes:
      - data-volume:/data/public
    networks:
      backend:

networks:
  frontend:
  backend:

volumes:
  static-volume:
  db-volume:
  conf-volume:
  data-volume:
  cache-volume:
