version: "3"
services:
  traefik:
    image: traefik:1.5
    labels:
      - "traefik.backend=traefik"
      - "traefik.docker.network=docker_frontend"
      - "traefik.frontend.rule=PathPrefix:/traefik;PathPrefixStrip:/traefik"
      - "traefik.enable=true"
      - "traefik.port=8080"
    expose:
      - "8080"
    command:
      - "--loglevel=DEBUG"
      - "--api"
      - "--docker"
      - "--docker.watch"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./_deploy/conf/traefik.toml:/etc/traefik/traefik.toml
      - ./_deploy/ssl/tls.key:/etc/ssl/tls.key
      - ./_deploy/ssl/tls.crt:/etc/ssl/tls.crt
    restart: always
    networks:
      frontend:
  nginx:
    image: nginx:1.13.8
    labels:
      - "traefik.backend=nginx"
      - "traefik.docker.network=docker_frontend"
      - "traefik.frontend.rule=PathPrefix:/static"
      - "traefik.enable=true"
      - "traefik.port=80"
    expose:
      - "80"
    volumes:
      - static-volume:/usr/share/nginx/html/static
    restart: always
    networks:
      frontend:
  wps:
    image: jasonb87/cwt_wps:2.0.2
    labels:
      - "traefik.backend=wps"
      - "traefik.docker.network=docker_frontend"
      - "traefik.frontend.rule=PathPrefix:/wps,/auth"
      - "traefik.enable=true"
      - "traefik.port=8000"
    # DEBUG-wps-entrypoint entrypoint: sleep infinity
    env_file:
      - ./_deploy/conf/app.properties
    expose:
      - "8000"
    volumes:
      - data-volume:/data/public
      - conf-volume:/etc/config
      - static-volume:/var/www/static
    restart: always
    networks:
      frontend:
      backend:
  postgres:
    image: postgres:9.6.2
    labels:
      - "traefik.enable=false"
    env_file:
      - ./_deploy/conf/app.properties
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always
    networks:
      frontend:
  redis:
    image: redis:3.2.8
    labels:
      - "traefik.enable=false"
    restart: always
    networks:
      frontend:
  celery:
    image: jasonb87/cwt_celery:2.0.2
    labels:
      - "traefik.enable=false"
    # DEBUG-celery-entrypoint entrypoint: sleep infinity
    command:
      - -Q low_prio
    env_file:
      - ./_deploy/conf/app.properties
    volumes:
      - conf-volume:/etc/config
      - data-volume:/data/public
      - cache-volume:/data/cache
      - user-volume:/data/user
      - tmp-volume:/data/tmp
    restart: always
    networks:
      frontend:
      backend:
  celery_beat:
    image: jasonb87/cwt_celery:2.0.2
    labels:
      - "traefik.enable=false"
    environment:
      - SUBCOMMAND=beat 
    env_file:
      - ./_deploy/conf/app.properties
    volumes:
      - conf-volume:/etc/config
      - data-volume:/data/public
      - cache-volume:/data/cache
      - user-volume:/data/user
      - tmp-volume:/data/tmp
    restart: always
    networks:
      frontend:
  thredds:
    image: jasonb87/cwt_thredds:4.6.10
    labels:
      - "traefik.backend=thredds"
      - "traefik.docker.network=docker_frontend"
      - "traefik.frontend.rule=PathPrefix:/threddsCWT"
      - "traefik.enable=true"
      - "traefik.port=8080"
    volumes:
      - data-volume:/data/public
    expose:
      - "8080"
    restart: always
    networks:
      frontend:
      backend:
  edas:
    image: jasonb87/cwt_edas:latest
    labels:
      - "traefik.enable=false"
    expose:
      - "5670"
      - "5671"
    volumes:
      - data-volume:/data/public
    restart: always
    networks:
      backend:

networks:
  frontend:
  backend:

volumes:
  static-volume:
  db-volume:
    driver: local-persist
    driver_opts:
      mountpoint: # PATH_DB
  conf-volume:
    driver: local-persist
    driver_opts: 
      mountpoint: # PATH_CONF
  data-volume:
    driver: local-persist
    driver_opts:
      mountpoint: # PATH_PUBLIC
  cache-volume:
    driver: local-persist
    driver_opts:
      mountpoint: # PATH_CACHE
  tmp-volume:
    driver: local-persist
    driver_opts:
      mountpoint: # PATH_TEMP
  user-volume:
    driver: local-persist
    driver_opts:
      mountpoint: # PATH_USER
