version: "3"
services:
  traefik:
    image: traefik:1.5
    labels:
      - "traefik.enable=false"
    command:
      - "--loglevel=DEBUG"
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--defaultentrypoints=http"
      - "--docker"
      - "--docker.watch"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    restart: always
    networks:
      frontend:
  wps:
    image: jasonb87/cwt_wps:2.0.0
    labels:
      - "traefik.backend=wps"
      - "traefik.docker.network=docker_frontend"
      - "traefik.frontend.rule=PathPrefix:/wps,/static,/auth"
      - "traefik.enable=true"
      - "traefik.port=8000"
    env_file:
      - ./_deploy/app.properties
    expose:
      - "8000"
    volumes:
      - data-volume:/data/public
      - conf-volume:/etc/config
      - static-volume:/var/www/static
    restart: always
    networks:
      frontend:
      backend:
  postgres:
    image: postgres:9.6.2
    labels:
      - "traefik.enable=false"
    env_file:
      - ./_deploy/app.properties
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always
    networks:
      frontend:
  redis:
    image: redis:3.2.8
    labels:
      - "traefik.enable=false"
    restart: always
    networks:
      frontend:
  celery:
    image: jasonb87/cwt_celery:2.0.0
    labels:
      - "traefik.enable=false"
    env_file:
      - ./_deploy/app.properties
    volumes:
      - conf-volume:/etc/config
      - data-volume:/data/public
      - cache-volume:/data/cache
      - user-volume:/data/user
      - tmp-volume:/data/tmp
    restart: always
    networks:
      frontend:
      backend:
  celery_beat:
    image: jasonb87/cwt_celery:2.0.0
    labels:
      - "traefik.enable=false"
    command: -l info -B
    env_file:
      - ./_deploy/app.properties
    volumes:
      - conf-volume:/etc/config
      - data-volume:/data/public
      - cache-volume:/data/cache
      - user-volume:/data/user
      - tmp-volume:/data/tmp
    restart: always
    networks:
      frontend:
  thredds:
    image: jasonb87/cwt_thredds:latest
    labels:
      - "traefik.backend=thredds"
      - "traefik.docker.network=docker_frontend"
      - "traefik.frontend.rule=PathPrefix:/threddsCWT"
      - "traefik.enable=true"
      - "traefik.port=8080"
    volumes:
      - data-volume:/data/public
    expose:
      - "8080"
    restart: always
    networks:
      frontend:
      backend:
  edas:
    image: jasonb87/cwt_edas:latest
    labels:
      - "traefik.enable=false"
    expose:
      - "5670"
      - "5671"
    volumes:
      - data-volume:/data/public
    restart: always
    networks:
      backend:

networks:
  frontend:
  backend:

volumes:
  static-volume:
  db-volume:
  conf-volume:
    driver: local-persist
    driver_opts: 
      mountpoint: ${PWD}/_deploy
  data-volume:
    driver: local-persist
    driver_opts:
      mountpoint: ${DEPLOY_DIR}/data/public
  cache-volume:
    driver: local-persist
    driver_opts:
      mountpoint: ${DEPLOY_DIR}/data/cache
  tmp-volume:
    driver: local-persist
    driver_opts:
      mountpoint: ${DEPLOY_DIR}/tmp
  user-volume:
    driver: local-persist
    driver_opts:
      mountpoint: ${DEPLOY_DIR}/user
