version: '3.3'
services:
  wps:
    image: jasonb87/cwt_wps:latest
    env_file:
      - ./common.env
    environment:
      - WPS_INIT=1
    configs:
      - source: wps_config
        target: /var/www/compute/compute/settings.py
    ports:
      - "8000:8000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      frontend:
      backend:
  postgres:
    image: postgres:9.6.2
    environment: 
      - POSTGRES_PASSWORD=1234
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      frontend:
  redis:
    image: redis:3.2.8
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      frontend:
  celery:
    image: jasonb87/cwt_celery:latest
    env_file:
      - ./common.env
    configs:
      - source: wps_config
        target: /var/www/compute/compute/settings.py
    volumes:
      - data-volume:/data/public
      - cache-volume:/data/cache
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '2.0'
    networks:
      frontend:
      backend:
  thredds:
    image: jasonb87/cwt_thredds:latest
    expose:
      - "8080"
    volumes:
      - data-volume:/data/public
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      backend:

configs:
  wps_config:
    file: ../compute/compute/settings.py

networks:
  frontend:
  backend:

volumes:
  data-volume:
  cache-volume:
