version: '3.3'
services:
  wps:
    image: jasonb87/cwt_wps:latest
    env_file:
      - ./common.env
    environment:
      - WPS_INIT=1
    ports:
      - "8000:8000"
    volumes:
      - conf-volume:/var/www/compute/compute
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      frontend:
      backend:
  postgres:
    image: postgres:9.6.2
    environment: 
      - POSTGRES_PASSWORD=1234
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      frontend:
  redis:
    image: redis:3.2.8
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      frontend:
  celery:
    image: jasonb87/cwt_celery:latest
    env_file:
      - ./common.env
    volumes:
      - conf-volume:/var/www/compute/compute
      - data-volume:/data/public
      - cache-volume:/data/cache
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '2.0'
    networks:
      frontend:
      backend:
  cdas:
    image: jasonb87/cwt_cdas2:latest
    expose:
      - "4356"
      - "4357"
    volumes:
      - data-volume:/data/public
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      backend:
  thredds:
    image: jasonb87/cwt_thredds:latest
    expose:
      - "8080"
    volumes:
      - data-volume:/data/public
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
    networks:
      backend:

networks:
  frontend:
  backend:

volumes:
  conf-volume:
  data-volume:
  cache-volume:
