apiVersion: v1
kind: Secret
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-app-secret
  labels:
    app: {{ template "esgf-compute-wps.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  oauth_client: {{ default "" .Values.wps.oauth.client | quote }}
  oauth_secret: {{ default "" .Values.wps.oauth.secret | quote }}
  postgres_password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
