{{- range .Values.celery.queues }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-celery-{{ .name }}
  labels:
    app: {{ $.Release.Name }}-celery-{{ .name }}
    chart: {{ template "esgf-compute-wps.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- if $.Values.celery.annotations }}
  annotations:
    {{ toYaml $.Values.celery.annotations | indent 2 }}
{{- end }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-celery-{{ .name }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-celery-{{ .name }}
        chart: {{ template "esgf-compute-wps.chart" $ }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
    spec:
      containers:
      - name: {{ $.Release.Name }}-celery-{{ .name }}
        image: {{ $.Values.celery.image }}:{{ $.Values.celery.imageTag }}
        {{- if not $.Values.development }}
        args: 
          - "celery"
          - "worker"
          - "-l"
          - "INFO"
          - "-c"
          - "1"
          - "--max-memory-per-child"
          - {{ $.Values.celery.resources.memory | quote }}
          - "-n"
          - {{ .name | quote }}
        {{- range $key, $value := .argsExtra }}
          - {{ $key | quote }}
          - {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if $.Values.development }}
        command:
          - sleep
          - infinity
        {{- end }}
        resources:
          {{- if not $.Values.development }}
          limits:
            cpu: {{ $.Values.celery.resources.cpuLimit | quote }}
            memory: {{ $.Values.celery.resources.memoryLimit | quote }}
          {{- end }}
          requests:
            cpu: {{ $.Values.celery.resources.cpuRequest | quote }}
            memory: {{ $.Values.celery.resources.memoryRequest | quote }}
        {{- if .ports }}
        ports:
        {{- range .ports }}
        - containerPort: {{ .port }}
          protocol: TCP
        {{- end }}
        {{- end }}
        env:
        {{- if $.Values.development }}
        - name: WPS_DEBUG
          value: "1"
        {{- end }}
        - name: AIRFLOW_HOME
          value: /etc/config
        - name: WPS_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "esgf-compute-wps.fullname" $ }}-app-config
              key: WPS_HOST
        - name: CELERY_BROKER
          valueFrom:
            configMapKeyRef:
              name: {{ template "esgf-compute-wps.fullname" $ }}-app-config
              key: CELERY_BROKER
        - name: CELERY_BACKEND
          valueFrom:
            configMapKeyRef:
              name: {{ template "esgf-compute-wps.fullname" $ }}-app-config
              key: CELERY_BACKEND
        - name: POSTGRES_HOST
          value: {{ template "postgresql.fullname" $ }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "esgf-compute-wps.fullname" $ }}-app-secret
              key: postgres_password
        volumeMounts:
        {{- if $.Values.development }}
        - mountPath: /var/www
          name: shared-volume
          subPath: shared
        {{- end }}
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /data/public
          name: public-volume
          subPath: public
        - mountPath: /data/cache
          name: cache-volume
          subPath: cache
        - mountPath: /data/ingress
          name: ingress-volume
          subPath: ingress
      volumes:
      {{- if $.Values.development }}
      - name: shared-volume
        hostPath:
          path: /opt/cwt/data/shared
      {{- end }}
      - name: config-volume
        configMap:
            name: {{ template "esgf-compute-wps.fullname" $ }}-django-config
      - name: public-volume
      {{- if $.Values.development }}
        hostPath:
          path: {{ $.Values.wps.data.ingressPath }}
          type: DirectoryOrCreate
      {{- else }}
        persistentVolumeClaim:
          claimName: public-pvc
      {{- end }}
      - name: cache-volume
      {{- if $.Values.development }}
        hostPath:
          path: {{ $.Values.wps.data.cachePath }}
          type: DirectoryOrCreate
      {{- else }}
        persistentVolumeClaim:
          claimName: cache-pvc
      {{- end }}
      - name: ingress-volume
      {{- if $.Values.development }}
        hostPath:
          path: {{ $.Values.wps.data.ingressPath }}
          type: DirectoryOrCreate
      {{- else }}
        persistentVolumeClaim:
          claimName: ingress-pvc
      {{- end }}
---
{{- end }}
