{{- $publicPath := .Values.data.publicPath }}
{{- $cachePath := .Values.data.cachePath }}
{{- range .Values.celery }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-celery-{{ .name }}
  labels:
    app: {{ $.Release.Name }}-celery-{{ .name }}
    chart: {{ template "esgf-compute-wps.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-celery-{{ .name }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-celery-{{ .name }}
        chart: {{ template "esgf-compute-wps.chart" $ }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
    spec:
      containers:
      - name: {{ $.Release.Name }}-celery-{{ .name }}
        image: {{ .image }}:{{ .imageTag }}
        {{- if not $.Values.development }}
        args: 
          - -l
          - info
          - -c
          - 1
          - --max-memory-per-child
          - {{ .resources.memory | quote }}
          - -n 
          - {{ .name }}
        {{- range $key, $value := .argsExtra }}
          - {{ $key | quote }}
          - {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if $.Values.development }}
        command:
          - sleep
          - infinity
        {{- end }}
        resources:
          limits:
            cpu: {{ .resources.cpuLimit | quote }}
            memory: {{ .resources.memoryLimit | quote }}
          requests:
            cpu: {{ .resources.cpuRequest | quote }}
            memory: {{ .resources.memoryRequest | quote }}
        env:
        {{- if $.Values.development }}
        - name: WPS_DEBUG
          value: "1"
        {{- end }}
        - name: WPS_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "esgf-compute-wps.fullname" $ }}-app-config
              key: WPS_HOST
        - name: CELERY_BROKER
          valueFrom:
            configMapKeyRef:
              name: {{ template "esgf-compute-wps.fullname" $ }}-app-config
              key: CELERY_BROKER
        - name: CELERY_BACKEND
          valueFrom:
            configMapKeyRef:
              name: {{ template "esgf-compute-wps.fullname" $ }}-app-config
              key: CELERY_BACKEND
        - name: POSTGRES_HOST
          value: {{ template "postgresql.fullname" $ }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "esgf-compute-wps.fullname" $ }}-app-secret
              key: postgres_password
        volumeMounts:
        {{- if $.Values.development }}
        - mountPath: /var/www
          name: shared-volume
        {{- end }}
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /data/public
          name: public-volume
        - mountPath: /data/cache
          name: cache-volume
        - mountPath: /data/ingress
          name: ingress-volume
      volumes:
      {{- if $.Values.development }}
      - name: shared-volume
        hostPath:
          path: {{ $.Values.sharedPath }}
      {{- end }}
      - name: config-volume
        configMap:
            name: {{ template "esgf-compute-wps.fullname" $ }}-django-config
      - name: public-volume
        hostPath:
          path: {{ $publicPath }}
          type: DirectoryOrCreate
      - name: cache-volume
        hostPath:
          path: {{ $cachePath }}
          type: DirectoryOrCreate
---
{{- end }}
