{{ if .Values.celery.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-celery-flower
  labels:
    app: {{ $.Release.Name }}-celery-flower
    chart: {{ template "esgf-compute-wps.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-celery-flower
      chart: {{ template "esgf-compute-wps.chart" $ }}
      release: {{ $.Release.Name }}
      heritage: {{ $.Release.Service }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-celery-flower
        chart: {{ template "esgf-compute-wps.chart" $ }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
    spec:
      {{- if .Values.celery.flower.nodeSelector }}
      nodeSelector: 
        {{ .Values.celery.flower.nodeSelector | toYaml | trimSuffix "\n" }}
      {{- end }}
      containers:
      - name: celery-flower
        image: {{ .Values.celery.image }}:{{ .Values.celery.imageTag }}
        command:
          - /bin/bash
          - -c
        args: ["cd /var/www/webapp/compute && PATH=/opt/conda/envs/wps/bin:$PATH celery flower -A compute -b redis://harping-bear-redis-master.default.svc/0 --address=0.0.0.0 --url-prefix=/celery"]
        ports:
        - containerPort: 5555
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-celery-flower
  labels:
    app: {{ $.Release.Name }}-celery-flower
    chart: {{ template "esgf-compute-wps.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  selector:
    app: {{ $.Release.Name }}-celery-flower
    chart: {{ template "esgf-compute-wps.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  ports:
  - protocol: TCP
    port: 5555
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-celery-flower
  lables:
    app: {{ $.Release.Name }}-celery-flower
    chart: {{ template "esgf-compute-wps.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}-celery-flower
          servicePort: 5555
        path: /celery
{{ end }}
