{{- range .Values.celery.queues }}
{{- $name := .name }}
{{- if .ingress }}
{{- $annotations := .ingress.annotations }}
{{- $path := .ingress.path }}
{{- range .ports }}
{{- $port := .port }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "esgf-compute-wps.fullname" $ }}-celery-{{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
{{- if $annotations }}
  annotations:
{{ toYaml $annotations | nindent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ template "esgf-compute-wps.fullname" $ }}-celery-{{ $name }}
          servicePort: {{ $port }}
      {{- if $path }}
        path: {{ $path }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
