{{- if .Values.cog.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cog
  labels:
    app: {{ .Release.Name }}-cog
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cog
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cog
        chart: {{ template "esgf-compute-wps.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ .Release.Name }}-cog
        image: {{ .Values.cog.image }}:{{ .Values.cog.imageTag }}
        imagePullPolicy: IfNotPresent
        {{- if and $.Values.cog.resources (not $.Values.development) (not $.Values.ignoreResources) }}
        resources: {{ $.Values.cog.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        {{- end }}
        args:
          - {{ .Values.wps.host | quote }}
          - "false"
          - "true"
          - "https://{{ .Values.wps.host }}/wps/home/configure"
          - "true"
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /usr/local/cog/cog_install/static
          name: static-volume
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
{{- end }}
