apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cog
  labels:
    app: {{ .Release.Name }}-cog
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cog
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cog
        chart: {{ template "esgf-compute-wps.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ .Release.Name }}-cog
        image: {{ .Values.cog.image }}:{{ .Values.cog.imageTag }}
        resources:
          limits:
            cpu: {{ .Values.cog.resources.cpuLimit | quote }}
            memory: {{ .Values.cog.resources.memoryLimit | quote }}
          requests:
            cpu: {{ .Values.cog.resources.cpuRequest | quote }}
            memory: {{ .Values.cog.resources.memoryRequest | quote }}
        args:
        {{- if .Values.cog.host }}
          - "{{ .Values.host }},{{ .Values.cog.host }}"
        {{- else }}
          - {{ .Values.host | quote }}
        {{- end }}
          - "false"
          - "true"
          - "https://{{ .Values.host }}/wps/home/configure"
          - "true"
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /usr/local/cog/cog_install/static
          name: static-volume
      volumes:
      - name: static-volume
        hostPath:
          path: {{ .Values.wps.staticPath }}
          type: DirectoryOrCreate
