apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cog
  labels:
    app: {{ .Release.Name }}-cog
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}-cog
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 8000
