apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dask-scheduler
  labels:
    app: {{ .Release.Name }}-dask-scheduler
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}-dask-scheduler
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 8786
    name: scheduler
  - protocol: TCP
    port: 8787
    name: bokeh
