{{- if .Values.edask.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-edask-scheduler
  labels:
    app: {{ .Release.Name }}-edask-scheduler
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.edask.dask.scheduler.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-edask-scheduler
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-edask-scheduler
        chart: {{ template "esgf-compute-wps.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ .Release.Name }}-edask-scheduler
        image: {{ .Values.edask.image }}:{{ .Values.edask.imageTag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: PATH
          value: /opt/conda/envs/edask/bin:$PATH
        command:
          - dask-scheduler
        resources:
          {{- if not .Values.development }}
          limits:
            cpu: {{ .Values.edask.resources.cpuLimit | quote }}
            memory: {{ .Values.edask.resources.memoryLimit | quote }}
          {{- end }}
          requests:
            cpu: {{ .Values.edask.resources.cpuRequest | quote }}
            memory: {{ .Values.edask.resources.memoryRequest | quote }}
        ports:
        - containerPort: 8786
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edask-scheduler
  labels:
    app: {{ .Release.Name }}-edask-scheduler
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}-edask-scheduler
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    name: push
    port: 8786
  - protocol: TCP
    name: web
    port: 8787
{{- end }}
