apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edas
  labels:
    app: {{ .Release.Name }}-edas
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}-edas
    release: {{ .Release.Name }}
  ports:
  - name: listen
    protocol: TCP
    port: 5670
  - name: send
    protocol: TCP
    port: 5671
