apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-edask-configmap
  labels:
    app: {{ template "esgf-compute-wps.name" . }}
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  app.conf: |
    wps.server.address=0.0.0.0
    request.port=5670
    response.port=5671
    sources.allowed=http
{{ if .Values.edask.scheduler }}
    dask.scheduler={{ .Values.edask.scheduler.address }}
{{ end }}
    cache.size.max=500M
    edask.cache.dir=/data/cache
  hosts: |
    localhost
    localhost
    localhost
