{{- if .Values.edask.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-edask-worker
  labels:
    app: {{ .Release.Name }}-edask-worker
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.edask.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-edask-worker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-edask-worker
        chart: {{ template "esgf-compute-wps.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ .Release.Name }}-edask-worker
        image: {{ .Values.edask.image }}:{{ .Values.edask.imageTag }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 9999
          initialDelaySeconds: 4
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9999
          initialDelaySeconds: 16
          periodSeconds: 20
        {{- if and $.Values.edask.worker.resources (not $.Values.development) (not $.Values.ignoreResources) }}
        resources: {{ $.Values.edask.worker.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        {{- end }}
        env:
        - name: PATH
          value: /opt/conda/envs/edask/bin:$PATH
        command:
          - dask-worker
          - --nthreads
          - "1"
          - --nprocs
          - "1"
          - --nanny-port
          - "9999"
          - {{ .Release.Name }}-edask-scheduler:8786
        ports:
        - containerPort: 8786
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edask-worker
  labels:
    app: {{ .Release.Name }}-edask-worker
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}-edask-worker
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 5670
{{- end }}
