apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-nginx
  labels:
    app: {{ template "esgf-compute-wps.fullname" . }}-nginx
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.nginx.annotations }}
  annotations:
  {{  toYaml .Values.nginx.annotations | indent 4 }} 
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /static
            backend:
              serviceName: {{ template "esgf-compute-wps.fullname" . }}-nginx
              servicePort: 80
