apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
        chart: {{ template "esgf-compute-wps.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      {{- if .Values.nginx.nodeSelector }}
      nodeSelector: 
        {{ .Values.nginx.nodeSelector | toYaml | trimSuffix "\n"}}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-nginx
        image: {{ .Values.nginx.image }}:{{ .Values.nginx.imageTag }}
        imagePullPolicy: IfNotPresent
        {{- if and $.Values.nginx.resources (not $.Values.development) (not $.Values.ignoreResources) }}
        resources: {{ $.Values.nginx.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        {{- end }}
