apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-provisioner
  labels:
    app: {{ .Release.Name }}-provisioner
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}-provisioner
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.provisioner.frontendPort }}
    name: frontend
  - port: {{ .Values.provisioner.backendPort }}
    name: backend
