apiVersion: v1
kind: Service
metadata:
  name: {{ template "esgf-compute-wps.fullname" $ }}-provisioner
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    app.kubernetes.io/component: provisioner
  ports:
  - port: {{ .Values.provisioner.frontendPort }}
    name: frontend
  - port: {{ .Values.provisioner.backendPort }}
    name: backend
