{{- if not .Values.development }}
{{- range .Values.wps.persistence }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - {{ .accessModes | default "ReadWriteOnce" }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass }}
{{- end }}
{{- end }}
