{{- if .Values.development }}
{{- range .Values.wps.persistence }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "esgf-compute-wps.fullname" $ }}-{{ .name }}-pvc
spec:
  storageClassName: {{ .storageClass }}
  accessModes:
    - {{ .accessModes }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
