apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-thredds
  labels:
    app: {{ .Release.Name }}-thredds
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ .Values.ingress.annotations }}
    {{ .Values.thredds.ingress.annotations }}
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/hsts-max-age: "31536000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/force-hsts: "true"
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.thredds.ingress.path }}
            backend:
              serviceName: {{ .Release.Name }}-thredds
              servicePort: 8080
