apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-thredds
  labels:
    app: {{ .Release.Name }}-thredds
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.thredds.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-thredds
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-thredds
        chart: {{ template "esgf-compute-wps.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ .Release.Name }}-thredds
        image: {{ .Values.thredds.image }}:{{ .Values.thredds.imageTag }}
        imagePullPolicy: IfNotPresent
        {{- if not $.Values.development }}
        resources:
          limits:
            cpu: {{ $.Values.thredds.resources.cpuLimit | quote }}
            memory: {{ $.Values.thredds.resources.memoryLimit | quote }}
          requests:
            cpu: {{ $.Values.thredds.resources.cpuRequest | quote }}
            memory: {{ $.Values.thredds.resources.memoryRequest | quote }}
        {{- end }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: public-volume
          mountPath: /data/public
          subPath: public
      volumes:
      - name: public-volume
        persistentVolumeClaim:
          claimName: public-pvc
