apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-thredds
  labels:
    app: {{ template "esgf-compute-wps.fullname" . }}-thredds
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.thredds.ingress.annotations }}
  annotations:
  {{ toYaml .Values.thredds.ingress.annotations | indent 2 }}
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.thredds.ingress.path }}
            backend:
              serviceName: {{ template "esgf-compute-wps.fullname" . }}-thredds
              servicePort: 8080
