apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-thredds
  labels:
    app: {{ .Release.Name }}-thredds
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.thredds.ingress.annotations }}
  annotations:
{{ toYaml .Values.thredds.ingress.annotations | nindent 4 }}
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.thredds.ingress.path }}
            backend:
              serviceName: {{ .Release.Name }}-thredds
              servicePort: 8080
