{{- if .Values.wps.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-wps
  labels:
    app: {{ .Release.Name }}-wps
    release: {{ .Release.Name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.wps.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /auth
        backend:
          serviceName: {{ .Release.Name }}-wps
          servicePort: 8000
      - path: /wps
        backend:
          serviceName: {{ .Release.Name }}-wps
          servicePort: 8000
{{- end }}
