apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-django-config
  labels:
    app: {{ template "esgf-compute-wps.name" . }}
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  airflow.cfg: |
    [core]
    airflow_home = /root/airflow
    dags_folder = /var/www/compute/compute/wps/dags
    base_log_folder = /root/airflow/logs
    remote_log_conn_id =
    encrypt_s3_logs = False
    logging_level = INFO
    logging_config_class =
    log_format = [%%(asctime)s] {%%(filename)s:%%(lineno)d} %%(levelname)s - %%(message)s
    simple_log_format = %%(asctime)s %%(levelname)s - %%(message)s
    executor = SequentialExecutor
    sql_alchemy_conn = postgres://postgres:abcd1234@{{ template "postgresql.fullname" . }}/postgres
    sql_alchemy_pool_size = 5
    sql_alchemy_pool_recycle = 3600
    parallelism = 32
    dag_concurrency = 16
    dags_are_paused_at_creation = True
    non_pooled_task_slot_count = 128
    max_active_runs_per_dag = 16
    load_examples = True
    plugins_folder = /root/airflow/plugins
    fernet_key = ihBd_PuQpY-PvV0rQOecuOa4sK2O5KbGb9tp4uEpThU=
    donot_pickle = False
    dagbag_import_timeout = 30
    task_runner = BashTaskRunner
    default_impersonation =
    security =
    unit_test_mode = False
    task_log_reader = file.task
    enable_xcom_pickling = True
    killed_task_cleanup_time = 60
    [cli]
    api_client = airflow.api.client.local_client
    endpoint_url = http://localhost:8080
    [api]
    auth_backend = airflow.api.auth.backend.default
    [operators]
    default_owner = Airflow
    default_cpus = 1
    default_ram = 512
    default_disk = 512
    default_gpus = 0
    [webserver]
    base_url = http://localhost:8080
    web_server_host = 0.0.0.0
    web_server_port = 8080
    web_server_ssl_cert =
    web_server_ssl_key =
    web_server_worker_timeout = 120
    worker_refresh_batch_size = 1
    worker_refresh_interval = 30
    secret_key = temporary_key
    workers = 4
    worker_class = sync
    access_logfile = -
    error_logfile = -
    expose_config = False
    authenticate = False
    filter_by_owner = False
    owner_mode = user
    dag_default_view = tree
    dag_orientation = LR
    demo_mode = False
    log_fetch_timeout_sec = 5
    hide_paused_dags_by_default = False
    page_size = 100
    [email]
    email_backend = airflow.utils.email.send_email_smtp
    [smtp]
    smtp_host = localhost
    smtp_starttls = True
    smtp_ssl = False
    smtp_port = 25
    smtp_mail_from = airflow@example.com
    [celery]
    celery_app_name = airflow.executors.celery_executor
    celeryd_concurrency = 16
    worker_log_server_port = 8793
    broker_url = redis://{{ template "redis.fullname" . }}/0
    celery_result_backend = redis://{{ template "redis.fullname" . }}/0
    flower_host = 0.0.0.0
    flower_port = 5555
    default_queue = default
    celery_config_options = airflow.config_templates.default_celery.DEFAULT_CELERY_CONFIG
    [dask]
    cluster_address = 127.0.0.1:8786
    [scheduler]
    job_heartbeat_sec = 5
    scheduler_heartbeat_sec = 5
    run_duration = -1
    min_file_process_interval = 0
    dag_dir_list_interval = 300
    print_stats_interval = 30
    child_process_log_directory = /root/airflow/logs/scheduler
    scheduler_zombie_task_threshold = 300
    catchup_by_default = True
    max_tis_per_query = 0
    statsd_on = False
    statsd_host = localhost
    statsd_port = 8125
    statsd_prefix = airflow
    max_threads = 2
    authenticate = False
    [ldap]
    uri = 
    user_filter = objectClass=*
    user_name_attr = uid
    group_member_attr = memberOf
    superuser_filter = 
    data_profiler_filter = 
    bind_user = cn=Manager,dc=example,dc=com
    bind_password = insecure
    basedn = dc=example,dc=com
    cacert = /etc/ca/ldap_ca.crt
    search_scope = LEVEL
    [mesos]
    master = localhost:5050
    framework_name = Airflow
    task_cpu = 1
    task_memory = 256
    checkpoint = False
    authenticate = False
    [kerberos]
    ccache = /tmp/airflow_krb5_ccache
    principal = airflow
    reinit_frequency = 3600
    kinit_path = kinit
    keytab = airflow.keytab
    [github_enterprise]
    api_rev = v3
    [admin]
    hide_sensitive_variable_fields = True

  unittests.cfg: |
    [core]
    unit_test_mode = True
    airflow_home = /root/airflow
    dags_folder = /root/airflow/dags
    plugins_folder = /root/airflow/plugins
    base_log_folder = /root/airflow/logs
    logging_level = INFO
    executor = SequentialExecutor
    sql_alchemy_conn = sqlite:////root/airflow/unittests.db
    load_examples = True
    donot_pickle = False
    dag_concurrency = 16
    dags_are_paused_at_creation = False
    fernet_key = 5YLk8_KG2PyGxNyzifizkOGLMAGHEPfxlFEhELBlP4M=
    non_pooled_task_slot_count = 128
    enable_xcom_pickling = False
    killed_task_cleanup_time = 5
    [cli]
    api_client = airflow.api.client.local_client
    endpoint_url = http://localhost:8080
    [api]
    auth_backend = airflow.api.auth.backend.default
    [operators]
    default_owner = airflow
    [webserver]
    base_url = http://localhost:8080
    web_server_host = 0.0.0.0
    web_server_port = 8080
    dag_orientation = LR
    dag_default_view = tree
    log_fetch_timeout_sec = 5
    hide_paused_dags_by_default = False
    page_size = 100
    [email]
    email_backend = airflow.utils.email.send_email_smtp
    [smtp]
    smtp_host = localhost
    smtp_user = airflow
    smtp_port = 25
    smtp_password = airflow
    smtp_mail_from = airflow@example.com
    [celery]
    celery_app_name = airflow.executors.celery_executor
    celeryd_concurrency = 16
    worker_log_server_port = 8793
    broker_url = sqla+mysql://airflow:airflow@localhost:3306/airflow
    celery_result_backend = db+mysql://airflow:airflow@localhost:3306/airflow
    flower_host = 0.0.0.0
    flower_port = 5555
    default_queue = default
    [scheduler]
    job_heartbeat_sec = 1
    scheduler_heartbeat_sec = 5
    authenticate = true
    max_threads = 2
    catchup_by_default = True
    scheduler_zombie_task_threshold = 300
    dag_dir_list_interval = 0
    max_tis_per_query = 0
    [admin]
    hide_sensitive_variable_fields = True

  django.properties: |
    [default]
    allowed.hosts={{ .Values.host }}
    active.user.threshold={{ .Values.wps.activeUserThreshold }}
    ingress.enabled={{ .Values.wps.ingressEnabled }}
    process.blacklist={{ .Values.wps.process.blacklist }}
    cert.download.enabled={{ .Values.wps.certDownloadEnabled }}

    [email]
    host={{ .Values.wps.email.host | default "localhost" }}
    port={{ .Values.wps.email.port | default 25 }}
    user={{ .Values.wps.email.user | default "" }}
    password={{ .Values.wps.email.password | default "" }}

    [wps]
    wps.dap=true
    wps.endpoint=http://{{ .Values.host }}/wps/
    wps.status_location=http://{{ .Values.host }}/wps/status/{job_id}/
    wps.dap_url=http://{{ .Values.host }}/threddsCWT/dodsC/public/{filename}
    wps.login_url=http://{{ .Values.host }}/wps/home/auth/login/openid
    wps.profile_url=http://{{ .Values.host }}/wps/home/user/profile
    wps.oauth2.callback=https://{{ .Values.host }}/auth/callback/
    wps.openid.trust.root=http://{{ .Values.host }}/
    wps.openid.return.to=http://{{ .Values.host }}/auth/callback/openid/
    wps.openid.callback.success=http://{{ .Values.host }}/wps/home/auth/login/callback
    wps.password.reset.url=http://{{ .Values.host }}/wps/home/auth/reset
    wps.ca.path=/tmp/certs
    wps.local.output.path=/data/public
    wps.user.temp.path=/tmp
    wps.admin.email=admin@aims2.llnl.gov
    wps.cache.path=/tmp/django/cache

    [cache]
    wps.cache.path=/data/cache
    wps.partition.size=10
    wps.cache.check=1
    wps.gb.max.size=2.097152e8
    wps.cache.max.age=30
    wps.cache.freed.percent=0.25

    [edas]
    wps.edas.host=edas
    wps.edas.timeout=30
    wps.edas.req.port=5670
    wps.edas.res.port=5671

    [ophidia]
    wps.oph.user=oph-test
    wps.oph.password=abcd
    wps.oph.host=aims2.llnl.gov
    wps.oph.port=11732
    wps.oph.output.path=/wps
    wps.oph.output.url=https://{{ .Values.host }}/thredds/dodsC{output_path}/{output_name}.nc
    wps.oph.default.cores=8
