apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-django-config
  labels:
    app: {{ template "esgf-compute-wps.name" . }}
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  django.properties: |
    [default]
    {{- if .Values.wps.allowedCIDR }}
    allowed.cidr={{ .Values.wps.allowedCIDR }}
    {{- end }}
    host={{ .Values.wps.host }}
    internal.lb={{ template "traefik.fullname" . }}.{{ .Release.Namespace }}.svc

    [email]
    host={{ required "Set wps.email.host" .Values.wps.email.host }}
    port={{ .Values.wps.email.port }}
    user={{ .Values.wps.email.user }}
    password={{ .Values.wps.email.password }}

    [wps]
    title={{ .Values.wps.title }}
    abstract={{ .Values.wps.abstract }}
    keywords={{ .Values.wps.keywords | join "," }}
    provider.name={{ .Values.wps.provider.name }}
    provider.site={{ .Values.wps.provider.site }}
    contact.name={{ .Values.wps.contact.name | default "Unknown" }}
    contact.position={{ .Values.wps.contact.position | default "Unknown" }}
    contact.phone={{ .Values.wps.contact.phone | default "Unknown" }}
    address.delivery={{ .Values.wps.address.delivery | default "Unknwon" }}
    address.city={{ .Values.wps.address.city | default "Unknwon" }}
    address.area={{ .Values.wps.address.area | default "Unknwon" }}
    address.postal={{ .Values.wps.address.postal | default "Unknwon" }}
    address.country={{ .Values.wps.address.country | default "Unknwon" }}
    address.email={{ .Values.wps.address.email | default "Unknwon" }}

    [output]
    fileserver.url={{ .Values.wps.externalHost }}/threddsCWT/fileServer/public/{filename}
    dodsc.url={{ .Values.wps.externalHost }}/threddsCWT/dodsC/public/{filename}
    local.path={{ .Values.wps.publicPath }}

    [server]
    external.url={{ .Values.wps.externalHost }}
    external.wps.url={{ .Values.wps.externalHost }}/wps/

    [external]
    jobs.url={{ .Values.wps.externalHost }}/user/jobs
    login.url={{ .Values.wps.externalHost }}/auth/login
    profile.url={{ .Values.wps.externalHost }}/user/profile
