apiVersion: v1
kind: Secret
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-app-secret
  labels:
    app: {{ template "esgf-compute-wps.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  OAUTH_CLIENT: {{ required "Set wps.oauth.client" .Values.wps.oauth.client | b64enc | quote }}
  OAUTH_SECRET: {{ required "Set wps.oauth.secret" .Values.wps.oauth.secret | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "Set postgresql.postgresqlPassword" .Values.postgresql.postgresqlPassword | b64enc | quote }}
  API_USERNAME: {{ required "Set wps.apiUsername" .Values.wps.apiUsername | b64enc | quote }}
  API_PASSWORD: {{ required "Set wps.apiPassword" .Values.wps.apiPassword | b64enc | quote }}
