apiVersion: v1
kind: Service
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-wps
  labels:
    app: {{ template "esgf-compute-wps.fullname" . }}-wps
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app: {{ template "esgf-compute-wps.fullname" . }}-wps
    release: {{ .Release.Name }}
