apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-django-config
  labels:
    app: {{ template "esgf-compute-wps.name" . }}
    chart: {{ template "esgf-compute-wps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  django.properties: |
    [default]
    {{- if .Values.wps.allowedCIDR }}
    allowed.cidr={{ .Values.wps.allowedCIDR }}
    {{- end }}
    host={{ .Values.wps.host }}
    celery.broker={{ template "redis.fullname" . }}-master:6379/0
    celery.backend={{ template "redis.fullname" . }}-master:6379/0
    internal.lb={{ .Values.wps.internalLB }}

    [email]
    host={{ .Values.wps.email.host }}
    port={{ .Values.wps.email.port }}
    user={{ .Values.wps.email.user }}
    password={{ .Values.wps.email.password }}

    [metrics]
    host=http://{{ .Values.wps.prometheus.host }}/prometheus/api/v1/query

    [dask]
    scheduler={{ .Release.Name }}-dask-scheduler:8786
    workers={{ .Values.dask.workers }}
    kube.namespace={{ .Values.dask.provisioner.namespace }}

    [wps]
    title={{ .Values.wps.title }}
    abstract={{ .Values.wps.abstract }}
    keywords={{ .Values.wps.keywords | join "," }}
    provider.name={{ .Values.wps.provider.name }}
    provider.site={{ .Values.wps.provider.site }}
    contact.name={{ .Values.wps.contact.name | default "Unknown" }}
    contact.position={{ .Values.wps.contact.position | default "Unknown" }}
    contact.phone={{ .Values.wps.contact.phone | default "Unknown" }}
    address.delivery={{ .Values.wps.address.delivery | default "Unknwon" }}
    address.city={{ .Values.wps.address.city | default "Unknwon" }}
    address.area={{ .Values.wps.address.area | default "Unknwon" }}
    address.postal={{ .Values.wps.address.postal | default "Unknwon" }}
    address.country={{ .Values.wps.address.country | default "Unknwon" }}
    address.email={{ .Values.wps.address.email | default "Unknwon" }}

    wps.ingress_path={{ .Values.wps.ingressPath }}
    wps.public_path={{ .Values.wps.publicPath }}

    wps.admin.email={{ .Values.wps.adminEmail | default "Unknown" }}
    wps.endpoint={{ .Values.wps.externalHost }}/wps/
    wps.status_location={{ .Values.wps.externalHost }}/api/status/{job_id}/
    wps.dap_url={{ .Values.wps.externalHost }}/threddsCWT/dodsC/public/{filename}
    wps.login_url={{ .Values.wps.externalHost }}/api/openid/login/
    wps.profile_url={{ .Values.wps.externalHost }}/user/profile
    wps.oauth2.callback={{ .Values.wps.externalHost }}/api/oauth2/callback/
    wps.openid.trust.root={{ .Values.wps.externalHost }}/
    wps.openid.return.to={{ .Values.wps.externalHost }}/api/openid/callback/
    wps.openid.callback.success={{ .Values.wps.externalHost }}/auth/login/callback

    [edas]
    wps.edas.enabled={{ .Values.edask.enabled }}
    wps.edas.host={{ .Release.Name }}-edask
    timeout.queue={{ .Values.edask.timeout.queue }}
    timeout.execute={{ .Values.edask.timeout.execute }}
