apiVersion: v1
kind: Secret
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-app-secret
  labels:
    app: {{ template "esgf-compute-wps.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  OAUTH_CLIENT: {{ .Values.wps.oauth.client | b64enc | quote }}
  OAUTH_SECRET: {{ .Values.wps.oauth.secret | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  API_USERNAME: {{ .Values.wps.apiUsername | b64enc | quote }}
  API_PASSWORD: {{ .Values.wps.apiPassword | b64enc | quote }}
