package:
  name: cwt-settings
  version: {{ environ.get('APP_VERSION', 'devel') }}

source:
  path: ./

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python

  run:
    - python
    - future
    - netaddr
    - configparser # [py27]

about:
  home: https://github.com/ESGF/esgf-compute-wps
  summary: LLNL ESGF Compute settings
