# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=128, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('request', models.PositiveIntegerField(default=4356)),
                ('response', models.PositiveIntegerField(default=4357)),
                ('status', models.IntegerField(default=1)),
                ('checked', models.DateTimeField(auto_now=True)),
                ('queue', models.PositiveIntegerField(default=0)),
                ('queue_size', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=128)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('capabilities', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.Server'),
        ),
    ]
