# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=128, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('request', models.PositiveIntegerField(default=4356)),
                ('response', models.PositiveIntegerField(default=4357)),
                ('status', models.IntegerField(default=1)),
                ('checked', models.DateTimeField(auto_now=True)),
                ('queue', models.PositiveIntegerField(default=0)),
                ('queue_size', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=128)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('capabilities', models.TextField()),
                ('processes', models.ManyToManyField(to='wps.Process')),
            ],
        ),
    ]
