# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('wps', '0001_db_server'), ('wps', '0002_db_server')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(max_length=64, unique=True)),
                ('is_wps', models.BooleanField(default=False)),
                ('queue', models.PositiveIntegerField(default=0)),
                ('queue_size', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
