# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0001_db_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
