# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0001_db_server_squashed_0002_db_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='request',
            field=models.IntegerField(default=4356),
        ),
        migrations.AddField(
            model_name='server',
            name='response',
            field=models.IntegerField(default=4357),
        ),
    ]
