# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstate',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
