# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0003_state_to_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('started', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='processes',
            field=models.ManyToManyField(to='wps.Process'),
        ),
    ]
