# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wps', '0004_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=256)),
                ('token_type', models.CharField(max_length=64)),
                ('refresh_token', models.CharField(max_length=64)),
                ('access_token', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=128)),
                ('expires_at', models.DateField()),
                ('api_key', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
