# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wps', '0012_auth_myproxyclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.TextField()),
                ('cert', models.TextField()),
                ('api_key', models.CharField(max_length=128)),
                ('extra', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mpc',
            name='user',
        ),
        migrations.RemoveField(
            model_name='oauth2',
            name='user',
        ),
        migrations.DeleteModel(
            name='MPC',
        ),
        migrations.DeleteModel(
            name='OAuth2',
        ),
    ]
