# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0013_auth_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='type',
            field=models.CharField(default='myproxyclient', max_length=64),
            preserve_default=False,
        ),
    ]
