# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0014_auth_missing_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('percent', models.PositiveIntegerField(null=True)),
                ('message', models.TextField(null=True)),
                ('exception', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='result',
        ),
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wps.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='report',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.Status'),
        ),
    ]
