# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0016_link_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='openid_url',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
