# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0019_job_extra_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
                ('dimensions', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('accessed_date', models.DateTimeField(auto_now=True)),
                ('size', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
