# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0020_cache_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
