# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0021_add_status_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('executed', models.PositiveIntegerField()),
                ('success', models.PositiveIntegerField()),
                ('failed', models.PositiveIntegerField()),
                ('retry', models.PositiveIntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.Process')),
            ],
        ),
    ]
