# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0022_process_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=256)),
                ('variable', models.CharField(max_length=64)),
                ('url', models.TextField()),
                ('requested', models.PositiveIntegerField()),
            ],
        ),
    ]
