# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0024_openid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
