# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0027_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
