# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0028_notifications_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='size',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
    ]
