# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0030_server_unique_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=128),
        ),
    ]
