# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0035_cache_accessed_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elapsed', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='process_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cache',
            name='url',
            field=models.CharField(max_length=513),
        ),
        migrations.AddField(
            model_name='timing',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.Process'),
        ),
    ]
