{% set data = load_setup_py_data() %}

package:
  name: compute-settings
  version: {{ data.get('version') }}

source:
  path: ./

build:
  build: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python

  run:
    - python
    - netaddr=0.7.19

about:
  home: https://github.com/ESGF/esgf-compute-wps
  summary: LLNL ESGF Compute settings
