#!/bin/bash

export PYWPS_CFG=/Developer/Projects/EclipseWorkspace/WPS/wps_cwt/wps_cds.cfg
#export PYWPS_PROCESSES=/Developer/Projects/EclipseWorkspace/WPS/wps_cwt/processes/

/Developer/Projects/EclipseWorkspace/WPS/PyWPS/wps.py
#/Developer/Projects/EclipseWorkspace/WPS/wps_cwt/mywps/wps.py
