#!/bin/bash

export PYWPS_CFG=/usr/local/cds/web/WPS/wps_cwt/wps_cds_cgi.cfg
export UVCDAT_SETUP_PATH=/Users/thomas/Development/uvcdat/master/build/install
export LD_LIBRARY_PATH=/Users/thomas/Development/uvcdat/master/build/install/Externals/lib
export PYTHONPATH=/Users/thomas/Development/uvcdat/master/build/install/Externals/lib/python2.7/site-packages
export DYLD_FALLBACK_LIBRARY_PATH=/Users/thomas/Development/uvcdat/master/build/install/Externals/lib

/usr/local/cds/web/WPS/PyWPS/wps.py

