apiVersion: v1
kind: Service
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-dask-scheduler
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    app.kubernetes.io/component: dask-scheduler
  ports:
  - protocol: TCP
    port: 8786
    name: scheduler
  - protocol: TCP
    port: 8787
    name: bokeh
