apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-kube-monitor
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: kube-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: kube-monitor
    spec:
      {{- if .Values.kubeMonitor.nodeSelector }}
      nodeSelector: 
        {{ .Values.kubeMonitor.nodeSelector | toYaml | trimSuffix "\n" }}
      {{- end }}
      serviceAccount: wps-dask
      restartPolicy: Always
      {{- if $.Values.kubeMonitor.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.kubeMonitor.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ template "esgf-compute-wps.name" . }}-kube-monitor
        image: {{ .Values.kubeMonitor.image }}:{{ .Values.kubeMonitor.imageTag }}
        imagePullPolicy: {{ .Values.kubeMonitor.imagePullPolicy }}
        resources: {{ $.Values.kubeMonitor.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        {{- if .Values.kubeMonitor.development }}
        command:
          - tini
          - --
        args:
          - /bin/sleep
          - infinity
        {{- end }}
        env:
        - name: REDIS_HOST 
          value: {{ template "redis.fullname" $ }}-master
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: TIMEOUT
          value: {{ .Values.kubeMonitor.timeout | quote }}
        {{- if .Values.kubeMonitor.development }}
        volumeMounts:
        - name: devel-volume
          mountPath: /devel
        {{- end }}
      volumes:
      {{- if .Values.kubeMonitor.development }}
      - name: devel-volume
        hostPath: 
          path: /opt/cwt/devel
          type: DirectoryOrCreate
      {{- end }}
