apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-nginx
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
{{- if .Values.nginx.ingress.labels }}
{{ toYaml .Values.nginx.ingress.labels | nindent 4 }}
{{- end }}
{{- if .Values.nginx.ingress.annotations }}
  annotations:
{{ toYaml .Values.nginx.ingress.annotations | nindent 4 }}
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "esgf-compute-wps.fullname" . }}-nginx
              servicePort: 80
