{{- range $key, $val := .Values.persistence.volumes }}
{{- if and $val $val.path }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $key }}-pv
  labels:
    name: {{ $key }}-pv
spec:
  capacity:
    storage: {{ $val.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $val.storageClassName }}
  hostPath:
    path: {{ $val.path }}
    type: DirectoryOrCreate
---
{{- end }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $key }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ $val.capacity }}
  storageClassName: {{ $val.storageClassName }}
  selector:
    matchLabels:
      name: {{ $key }}-pv
---
{{- end }}
