{{- range $.Values.wps.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "esgf-compute-wps.fullname" $ }}-wps
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    app.kubernetes.io/component: wps
  ports:
    - port: {{ .port }}
      protocol: TCP
      name: {{ .name }}
{{- end }}
