apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower
  labels:
    app: celery-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-flower
  template:
    metadata:
      labels:
        app: celery-flower
    spec:
      containers:
      - name: celery-flower
        image: jasonb87/cwt_celery:devel
        command:
          - /bin/bash
          - -c
        args: ["cd /var/www/webapp/compute && PATH=/opt/conda/envs/wps/bin:$PATH celery flower -A compute -b redis://harping-bear-redis-master.default.svc/0 --address=0.0.0.0 --url-prefix=/celery"]
        ports:
        - containerPort: 5555
#        volumeMounts:
#        - mountPath: /data
#          name: data-volume
#        - mountPath: /etc/config
#          readOnly: true
#          name: celery-flower-secret
#        - mountPath: /etc/config
#          name: celery-flower-config
#      nodeSelector:
#        tier: frontend
#      volumes:
#      - name: data-volume
#        persistentVolumeClaim:
#          claimName: data-volume
#      - name: celery-flower-secret
#        secret:
#          secretName: celery-flower
#      - name: celery-flower-config
#        configMap:
#          name: celery-flower
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: celery-flower
#data:
#  test.txt: |
#    hello=world
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: celery-flower
#type: Opaque
#data:
#  username: hello
---
kind: Service
apiVersion: v1
metadata:
  name: celery-flower
spec:
  selector:
    app: celery-flower
  ports:
  - protocol: TCP
    port: 5555
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: celery-flower
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: celery-flower
          servicePort: 5555
        path: /celery
---
