cluster:
  env:
    MINIMUM_MASTER_NODES: "1"

client:
  replicas: 1

master:
  replicas: 2

  persistence:
    storageClass: local-storage

data:
  replicas: 1

  persistence:
    storageClass: local-storage
