host: 0.0.0.0
development: false

prometheus:
  server:
    prefixURL: /prometheus
    baseURL: /prometheus

    ingress:
      enabled: true
      hosts:
      - /prometheus

    persistentVolume:
      enabled: true
      size: 10Gi
      storageClass: slow

traefik:
  serviceType: NodePort

  #ssl:
    #enabled: true
    #enforced: true
    #defaultCert:
    #defaultKey:

  cpuLimit: 200m
  memoryLimit: 256Mi

  rbac:
    enabled: true

  deployment:
    hostPort:
      httpEnabled: true
      httpsEnabled: true

  dashboard:
    enabled: true
    domain: ""

    # Recommend editing the ingress object and adding a path /traefik
    ingress:
      annotations:
        #traefik.ingress.kubernetes.io/whitelist-source-range: ""
        traefik.frontend.rule.type: PathPrefixStrip
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/hsts-max-age: "31536000"
        ingress.kubernetes.io/hsts-include-subdomains: "true"
        ingress.kubernetes.io/force-hsts: "true"

nginx:
  replicas: 1
  image: nginx
  imageTag: 1.13.8

  resources:
    cpuRequest: 100m
    memoryRequest: 128Mi
    cpuLimit: 1000m
    memoryLimit: 256Mi
  
wps:
  replicas: 1
  image: jasonb87/cwt_wps
  imageTag: 2.1.0
  staticPath: /opt/nfs/cwt/static
  activeUserThreshold: 5
  ingressEnabled: true
  certDownloadEnabled: true

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /wps/metrics
    prometheus.io/port: "8000"

  data:
    sharedPath: /opt/cwt/data/shared
    staticPath: /opt/cwt/data/static
    publicPath: /opt/cwt/data/public
    cachePath: /opt/cwt/data/cache
    ingressPath: /opt/cwt/data/ingress
  
  process:
    blacklist: "[]"

  resources:
    cpuRequest: 100m
    memoryRequest: 128Mi
    cpuLimit: 1000m
    memoryLimit: 256Mi

  oauth:
    client: ""
    secret: ""

  email:
    host: "localhost"

  ports:
    - name: django
      port: 8000

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"

celery:
  image: jasonb87/cwt_celery
  imageTag: 2.1.0

  metrics: /data/metrics

  resources:
    # Must quote the memory field otherwise large numbers are rendered in
    # scientific notation which celery does not like. This value is in KiB.
    memory: "1024000"
    cpuRequest: 100m
    memoryRequest: 128Mi
    cpuLimit: 1000m
    memoryLimit: 1Gi

  persistence:
    public:
      storageClassName: slow
      size: 10Gi

    ingress:
      storageClassName: slow
      size: 10Gi

    cache:
      storageClassName: slow
      size: 10Gi

  queues:
  - name: ingress
    replicas: 1
    argsExtra:
      "-c": 1
      "-Q": ingress
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
    ports:
      - port: 8080
        name: metrics

  - name: priority-low
    replicas: 1
    argsExtra:
      "-c": 1
      "-Q": priority.low
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
    ports:
      - port: 8080
        name: metrics

  - name: priority-high
    replicas: 1
    argsExtra:
      "-c": 1
      "-Q": priority.high
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
    ports:
      - port: 8080
        name: metrics

thredds:
  replicas: 1
  image: jasonb87/cwt_thredds
  imageTag: 4.6.10

  resources:
    cpuRequest: 100m
    memoryRequest: 128Mi
    cpuLimit: 1000m
    memoryLimit: 512Mi

  ingress:
    path: /threddsCWT
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"

postgresql:
  postgresPassword: abcd1234
  persistence:
    enabled: true
    storageClass: slow
    size: 10Gi

redis:
  repository: redis
  tag: 4.0.10

  cluster:
    enabled: false

  usePassword: false

  master:
    persistence:
      enabled: false

    service:
      type: ClusterIP

    securityContext:
      enabled: false

edas:
  enabled: false
  replicas: 1
  image: jasonb87/cwt_edas
  imageTag: latest

  resources:
    cpuRequest: 100m
    memoryRequest: 128Mi
    cpuLimit: 1000m
    memoryLimit: 512Mi

cog:
  enabled: false
  replicas: 1
  image: jasonb87/cwt_cog
  imageTag: latest

  resources:
    cpuRequest: 100m
    memoryRequest: 128Mi
    cpuLimit: 1000m
    memoryLimit: 256Mi

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"
