development: false

ingress:
  annotations:

wps:
  replicas: 1
  image: jasonb87/cwt_wps
  imageTag: 2.0.2
  cpuRequest: 100m
  memoryRequest: 128Mi
  cpuLimit: 1000m
  memoryLimit: 1Gi
  staticPath: /opt/nfs/cwt/static
  host: 10.5.5.5

  oauth:
    client: ""
    secret: ""

  email:
    host: "localhost"

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true

postgresql:
  postgresPassword: abcd1234
  persistence:
    enabled: false

redis:
  cluster:
    enabled: false
  usePassword: false
