development: false

persistence:
  cache:
    storageClassName: slow
    capacity: 10Gi
    path: /opt/nfs/cwt

  public:
    storageClassName: slow
    capacity: 100Gi
    path: /opt/nfs/cwt

  postgresql:
    storageClassName: slow
    capacity: 10Gi
    path: /opt/cwt

  postgresql-backup:
    storageClassName: slow
    capacity: 10Gi
    path: /opt/nfs/cwt

  redis:
    storageClassName: slow
    capacity: 10Gi
    path: /opt/cwt

nginx:
  replicas: 1
  image: jasonb87/cwt_webapp
  imageTag: devel

  nodeSelector:
    tier: backend

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"
  
wps:
  replicas: 1
  image: jasonb87/cwt_wps
  imageTag: devel
  host: aims2.llnl.gov
  externalHost: https://aims2.llnl.gov
  allowedCIDR: 172.17.0.0/16

  nodeSelector:
    tier: backend

  ingressPath: /data/ingress
  publicPath: /data/public

  adminEmail:

  title: "LLNL WPS Server"
  abstract: "LLNL WPS Compute Service"
  keywords:
    - "WPS"

  provider:
    name: "Jason B."
    site: "https://aims2.llnl.gov"

  contact:
    name:
    position:
    phone:

  address: 
    delivery:
    city:
    area:
    postal:
    counter:
    email:
    
  prometheus:
    host: mottled-mouse-prometheus-server.default.svc

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /wps/metrics
    prometheus.io/port: "8000"

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  worker:
    cpuCount: 3
    cpuUnits: 100
    memory: "200000000"
    userPercent: 0.10

  oauth:
    client: ""
    secret: ""

  email:
    host: "localhost"
    port: 25
    user: "wps"
    password: ""

  ports:
    - name: django
      port: 8000

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"

celery:
  image: jasonb87/cwt_celery
  imageTag: devel
  metrics: /metrics

  nodeSelector:
    tier: backend

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi

  flower:
    enabled: false

  queues:
  - name: ingress
    replicas: 1
    argsExtra:
      "-c": 1
      "-Q": ingress
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
    ports:
      - port: 8080
        name: metrics

  - name: edask
    replicas: 1
    argsExtra:
      "-c": 1
      "-Q": edask
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
    ports:
      - port: 8080
        name: metrics

thredds:
  replicas: 1
  image: jasonb87/cwt_thredds
  imageTag: 4.6.10

  nodeSelector:
    tier: backend

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  ingress:
    path: /threddsCWT
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"

postgresql:
  postgresUsername: postgres
  postgresPassword: abcd1234
  port: 5432

  nodeSelector:
    tier: database

  master:
    nodeSelector:
      tier: database

  persistence:
    enabled: true
    existingClaim: postgresql-pvc

  backup:
    enabled: false
    image: bitnami/postgresql
    tag: 10.6.0

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

redis:
  image:
    repository: redis
    tag: 4.0.10

  cluster:
    enabled: false

  usePassword: false

  persistence:
    existingClaim: redis-pvc

  master:
    service:
      type: ClusterIP

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    nodeSelector:
      tier: database

    securityContext:
      enabled: false

edask:
  enabled: false
  replicas: 1
  image: jasonb87/cwt_edask
  imageTag: latest

  nodeSelector:
    tier: backend

  timeout:
    queue: 30
    execute: 300

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Gi

  scheduler:
    address: innocent-deer-edask-scheduler.default.svc:8786

    nodeSelector:
      tier: backend

    replicas: 1

    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi

  worker:
    replicas: 1

    nodeSelector:
      tier: backend

    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
