development: false

traefik:
  serviceType: NodePort

  rbac:
    enabled: true

  resources:
    requests:
      cpu: 200m
      memory: 256Mi

    limits:
      cpu: 500m
      memory: 512Mi

  ssl:
    enabled: true
    enforced: true
    tlsMinVersion: VersionTLS12
    cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
    generateTLS: true
    
  dashboard:
    enabled: true
    domain: ""
    ingress:
      annotations:
        ingress.kubernetes.io/auth-type: basic
        ingress.kubernetes.io/auth-secret: traefik-auth
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/hsts-max-age: "31536000"
        ingress.kubernetes.io/hsts-include-subdomains: "true"
        ingress.kubernetes.io/force-hsts: "true"
      labels:
        traffic-type: external

  kubernetes:
    labelSelector: traffic-type=internal

  metrics:
    prometheus:
      enabled: true
      restrictAccess: true

persistence:
  cache:
    storageClassName: slow
    capacity: 10Gi
    path: /p/cscratch/nimbus/wps/data/cache

  public:
    storageClassName: slow
    capacity: 100Gi
    path: /p/cscratch/nimbus/wps/data/public

  postgresql:
    storageClassName: slow
    capacity: 10Gi
    path: /opt/nimbus/wps/postgresql

  # postgresql-backup:
  #   storageClassName: slow
  #   capacity: 10Gi
  #   path: /opt/nimbus/wps/postgresql-backup

  redis:
    storageClassName: slow
    capacity: 10Gi
    path: /opt/nimbus/wps/redis

dask:
  image: jasonb87/cwt_celery
  imageTag: devel

  imagePullPolicy: Always

  workers: 10

  nthreads: 4
  nprocs: 1
  memoryLimit: 8GB

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    request:
      cpu: 4
      memory: 8Gi

  provisioner:
    image: jasonb87/cwt_dask_provisioner
    imageTag: devel

    imagePullPolicy: Always

    timeout: 120

    nodeSelector:
      tier: backend

    namespace: production

    resources:
      limits:
        cpu: 1
        memory: 512Mi

      requests:
        cpu: 500m
        memory: 256Mi

  scheduler:
    nodeSelector:
      tier: backend

    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /daskboard/metrics
      prometheus.io/port: "8787"

    ingress:
      annotations:
        ingress.kubernetes.io/auth-type: basic
        ingress.kubernetes.io/auth-secret: traefik-auth
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/hsts-max-age: "31536000"
        ingress.kubernetes.io/hsts-include-subdomains: "true"
        ingress.kubernetes.io/force-hsts: "true"
      labels:
        traffic-type: external

    resources:
      limits:
        cpu: 2
        memory: 1Gi
      requests:
        cpu: 1
        memory: 512Mi

nginx:
  replicas: 1
  image: jasonb87/cwt_webapp
  imageTag: devel

  nodeSelector:
    tier: backend

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"
    labels:
      traffic-type: external
  
wps:
  replicas: 1
  image: jasonb87/cwt_wps
  imageTag: devel
  imagePullPolicy: Always

  host: aims2.llnl.gov
  externalHost: https://aims2.llnl.gov
  allowedCIDR: 172.17.0.0/16

  apiUsername:
  apiPassword:

  prometheus:
    host:

  nodeSelector:
    tier: backend

  ingressPath: /data/ingress
  publicPath: /data/public

  adminEmail:

  title: "LLNL WPS Server"
  abstract: "LLNL WPS Compute Service"
  keywords:
    - "WPS"

  provider:
    name: "Jason B."
    site: "https://aims2.llnl.gov"

  contact:
    name:
    position:
    phone:

  address: 
    delivery:
    city:
    area:
    postal:
    counter:
    email:

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /api/metrics/
    prometheus.io/port: "8000"

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  oauth:
    client:
    secret:

  email:
    host: 
    port: 25
    user: ""
    password: ""

  ports:
    - name: django
      port: 8000

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"
    external:
      labels:
        traffic-type: external
    internal:
      labels:
        traffic-type: internal

celery:
  image: jasonb87/cwt_celery
  imageTag: devel
  metrics: /metrics

  nodeSelector:
    tier: backend

  imagePullPolicy: Always

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi

  flower:
    enabled: false

  queues:
  - name: ingress
    replicas: 1
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
    ports:
      - port: 8080
        name: metrics

  - name: edask
    replicas: 1
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
    ports:
      - port: 8080
        name: metrics

thredds:
  replicas: 1
  image: jasonb87/cwt_thredds
  imageTag: 4.6.10

  nodeSelector:
    tier: backend

  heapMax: 2g
  heapInit: 512m

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi

  ingress:
    path: /threddsCWT
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"
    labels:
      traffic-type: external

postgresql:
  postgresqlUsername: postgres
  postgresqlPassword:
  port: 5432

  nodeSelector:
    tier: backend

  master:
    nodeSelector:
      tier: backend
      storage/wps: local

  persistence:
    enabled: true
    existingClaim: postgresql-pvc

  backup:
    enabled: false
    image: bitnami/postgresql
    tag: 10.6.0

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

redis:
  cluster:
    enabled: false

  usePassword: false

  # Cannot use permission init container when using existing claim 
  # chown -R 1001:1001
  persistence:
    existingClaim: redis-pvc

  master:
    service:
      type: ClusterIP

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    nodeSelector:
      tier: backend
      storage/wps: local

edask:
  enabled: false
  replicas: 1
  image: jasonb87/cwt_edask
  imageTag: latest
  imagePullPolicy: Always

  nodeSelector:
    tier: backend

  timeout:
    queue: 30
    execute: 300

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
