development: false

data:
  publicPath: /opt/nfs/cwt/data/public
  cachePath: /opt/nfs/cwt/data/cache

ingress:
  annotations:

wps:
  replicas: 1
  image: jasonb87/cwt_wps
  imageTag: 2.0.2
  staticPath: /opt/nfs/cwt/static
  host: 10.5.5.5

  resources:
    cpuRequest: 100m
    memoryRequest: 128Mi
    cpuLimit: 1000m
    memoryLimit: 512Mi

  oauth:
    client: ""
    secret: ""

  email:
    host: "localhost"

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true

celery:
  - name: default
    replicas: 1
    image: jasonb87/cwt_celery
    imageTag: 2.0.2

    resources:
      # Must quote the memory field otherwise large numbers are rendered in
      # scientific notation which celery does not like. This value is in KiB.
      memory: "1024000"
      cpuRequest: 100m
      memoryRequest: 128Mi
      cpuLimit: 1000m
      memoryLimit: 1Gi

  - name: beat
    replicas: 1
    image: jasonb87/cwt_celery
    imageTag: 2.0.2
    argsExtra: "-B"

    resources:
      # Must quote the memory field otherwise large numbers are rendered in
      # scientific notation which celery does not like. This value is in KiB.
      memory: "1024000"
      cpuRequest: 100m
      memoryRequest: 128Mi
      cpuLimit: 1000m
      memoryLimit: 1Gi

postgresql:
  enabled: false
  postgresPassword: abcd1234
  persistence:
    enabled: false

redis:
  cluster:
    enabled: false

  usePassword: false

  master:
    persistence:
      enabled: false

    service:
      type: ClusterIP

    securityContext:
      enabled: false
