{% set data = load_setup_py_data() %}

package:
  name: compute-provisioner
  version: {{ data.get('version') }}

source:
  path: ./

build:
  noarch: python
  build: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - pyzmq=18.0.1
    - redis-py=3.2.1
    - python-kubernetes=9.0.0

test:
  imports:
    - compute_provisioner
    - compute_provisioner.load_balancer

about:
  home: https://github.com/ESGF/esgf-compute-wps
  summary: A Kubernetes compute provisioner.
