package:
  name: esgf-compute-wps
  version: {{ environ.get('APP_VERSION', 'devel') }}

source:
  git_url: ../../

build:
  string: py{{ PY_VER }}_{{ GIT_DESCRIBE_HASH }}
  script: python compute/wps/setup.py install --single-version-externally --record=record.txt
  noarch: python

requirements:
  build:
    - git

  host:
    - python

  run:
    - python

about:
  home: https://github.com/ESGF/esgf-compute-wps
  summary: LLNL WPS Django Application
