package:
  name: esgf-compute-wps
  version: {{ environ.get('APP_VERSION', 'devel') }}

source:
  path: ./

build:
  noarch: python
  build: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - nomkl
    - django=1.11
    - django-cors-headers
    - djangorestframework
    - django-grappelli
    - django-allow-cidr
    - cdms2=3.1.2
    - libcdms=3.1.2
    - cdutil
    - bjoern
    - pyophidia
    - esgf-compute-api={{ environ.get('APP_VERSION', 'devel') }}
    - jinja2
    - myproxyclient
    - future
    - gunicorn
    - psycopg2
    - python-openid # [py27]
    - python3-openid # [py3k]
    - pyzmq
    - redis-py
    - requests
    - requests-oauthlib
    - celery
    - prometheus_client
    - cwt-settings={{ environ.get('APP_VERSION', 'devel') }}
    - cwt-kubernetes={{ environ.get('APP_VERSION', 'devel') }}
    - xarray
    - python-coreapi

about:
  home: https://github.com/ESGF/esgf-compute-wps
  summary: LLNL WPS Django Application
