version: '2'
services:
  thredds:
    image: jasonb87/thredds
    ports:
      - "8080:8080"
    volumes:
      - /data  

  wps:
    image: jasonb87/esgf_wps
    links:
      - thredds
      - ophidia
    ports:
      - "8000:8000"
    volumes_from:
      - thredds

  ophidia:
    image: jasonb87/ophidia
    entrypoint:
      - ./entrypoint.sh
      - sleep
      - infinity
    expose:
      - "11732"
      - "443"
    links:
      - thredds
    ports:
      - "80:80"
    volumes_from:
      - thredds
