# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('wps', '0002_jobstate_created'), ('wps', '0003_state_to_status'), ('wps', '0004_process'), ('wps', '0005_oauth2'), ('wps', '0006_multi_backends'), ('wps', '0007_process_identifier_unique'), ('wps', '0008_status_store_string'), ('wps', '0009_oauth2_primary_key'), ('wps', '0010_oauth_openid_textfield'), ('wps', '0011_remove_unused_oauth2_fields'), ('wps', '0012_auth_myproxyclient'), ('wps', '0013_auth_update'), ('wps', '0014_auth_missing_type_field'), ('wps', '0015_job_overhaul'), ('wps', '0016_link_user_job'), ('wps', '0017_store_openid_url'), ('wps', '0018_status_update'), ('wps', '0019_job_extra_field'), ('wps', '0020_cache_tracking'), ('wps', '0021_add_status_updated'), ('wps', '0022_process_usage'), ('wps', '0023_file_tracking'), ('wps', '0024_openid'), ('wps', '0025_tracking_update'), ('wps', '0026_user_link_file_process'), ('wps', '0027_notifications'), ('wps', '0028_notifications_extension'), ('wps', '0029_cache_size_conversion_byte_gigabyte'), ('wps', '0030_server_unique_host'), ('wps', '0031_remove_instance_model'), ('wps', '0032_process_toggle'), ('wps', '0033_server_fix'), ('wps', '0034_process_abstract'), ('wps', '0035_cache_accessed_fix'), ('wps', '0036_process_timing'), ('wps', '0037_cdat_update'), ('wps', '0038_improved_progress'), ('wps', '0039_cache_update'), ('wps', '0040_update_process'), ('wps', '0041_auto_20190322_2032'), ('wps', '0042_remove_cache')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstate',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameModel(
            old_name='JobState',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='state',
            new_name='status',
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('backend', models.CharField(default='cdas2', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='processes',
            field=models.ManyToManyField(to='wps.Process'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.TextField()),
                ('api_key', models.CharField(max_length=128)),
                ('extra', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(default='myproxyclient', max_length=64)),
                ('openid_url', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('percent', models.PositiveIntegerField(null=True)),
                ('message', models.TextField(null=True)),
                ('exception', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='result',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wps.Status'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='message',
            name='exception',
        ),
        migrations.AddField(
            model_name='job',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wps.Process'),
        ),
        migrations.AddField(
            model_name='status',
            name='exception',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='extra',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=256)),
                ('variable', models.CharField(max_length=64)),
                ('url', models.TextField()),
                ('requested', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenIDAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(max_length=2048)),
                ('handle', models.CharField(max_length=256)),
                ('secret', models.TextField(max_length=256)),
                ('issued', models.IntegerField()),
                ('lifetime', models.IntegerField()),
                ('assoc_type', models.TextField(max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenIDNonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(max_length=2048)),
                ('timestamp', models.IntegerField()),
                ('salt', models.CharField(max_length=40)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='files',
            unique_together=set([('name', 'host')]),
        ),
        migrations.AlterUniqueTogether(
            name='openidnonce',
            unique_together=set([('server_url', 'timestamp', 'salt')]),
        ),
        migrations.AlterUniqueTogether(
            name='openidassociation',
            unique_together=set([('server_url', 'handle')]),
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now=True)),
                ('requested', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now=True)),
                ('requested', models.PositiveIntegerField(default=0)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.Process')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.File'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='process',
            name='abstract',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='steps_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='steps_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='process',
            name='metadata',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='version',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='process',
            name='identifier',
            field=models.CharField(max_length=128),
        ),
        migrations.RemoveField(
            model_name='process',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=set([('identifier', 'version')]),
        ),
        migrations.AlterField(
            model_name='status',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='wps.Job'),
        ),
    ]
