# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0002_jobstate_created_squashed_0042_remove_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='openid_url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='auth',
            name='type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='backend',
            field=models.CharField(max_length=128),
        ),
    ]
