# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0003_squash_support'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set([('job', 'status')]),
        ),
    ]
