# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0005_remove_job_progress_add_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='server',
        ),
    ]
