# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0007_process_identifier_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=64),
        ),
    ]
