# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0031_remove_instance_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
