# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0033_server_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='abstract',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
