# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-22 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0038_improved_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='openid',
        ),
        migrations.AddField(
            model_name='cache',
            name='local_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='cache',
            name='variable',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cache',
            name='accessed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='size',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='url',
            field=models.CharField(max_length=512),
        ),
        migrations.RemoveField(
            model_name='cache',
            name='uid',
        ),
        migrations.AlterUniqueTogether(
            name='cache',
            unique_together=set([('url', 'variable')]),
        ),
    ]
