# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0039_cache_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='metadata',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='version',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='process',
            name='identifier',
            field=models.CharField(max_length=128),
        ),
        migrations.RemoveField(
            model_name='process',
            name='description',
        ),
        migrations.RemoveField(
            model_name='process',
            name='enabled',
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=set([('identifier', 'version')]),
        ),
    ]
