# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wps', '0041_auto_20190322_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cache',
        ),
    ]
