apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler-{{ user }}
spec:
  selector:
    compute.io/component: scheduler
  ports:
  - protocol: TCP
    port: 8786
    name: scheduler
  - protocol: TCP
    port: 8787
    name: dashboard
