apiVersion: v1
kind: ConfigMap
metadata:
  name: dask-configmap-{{ user }}
data:
  kubernetes.yaml: |
    kubernetes:
      name: "dask-worker-{user}-{uuid}"
      port: 8786
      worker-template:
        kind: Pod
        metadata:
          labels:
          {%- for label in labels %}
            {{ label }}
          {%- endfor %}
        spec:
          restartPolicy: Never
          imagePullSecrets:
          - name: {{ image_pull_secret }}
          containers:
          - name: dask-worker
            image: {{ image }}
            imagePullPolicy: {{ image_pull_policy }}
            env:
            - name: CDAT_ANONYMOUS_LOG
              value: 'no'
            - name: HDF5_USE_FILE_LOCKING
              value: 'FALSE'
            - name: REDIS_HOST
              value: {{ redis_host }}
            - name: REDIS_PORT
              value: {{ redis_port }}
            - name: REDIS_DB
              value: {{ redis_db }}
            args:
              - dask-worker
              - --nthreads
              - "{{ worker_nthreads }}"
              - --no-bokeh
              - --memory-limit
              - "{{ worker_memory }}"
              - --death-timeout
              - '60'
            {%- if worker_redis_cache_enabled %}
              - --worker-class
              - compute_tasks.dask_worker.CachedWorker
            {%- endif %}
            resources:
              limits:
                cpu: {{ worker_cpu }}
                memory: {{ worker_memory }}
              requests:
                cpu: {{ worker_cpu }}
                memory: {{ worker_memory }}
            volumeMounts:
              - name: data
                mountPath: /data/public
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ data_claim_name }}
