apiVersion: v1
kind: Pod
metadata:
  name: dask-scheduler-{{ user }}
  labels:
    app.kubernetes.io/dask-component: scheduler
    app.kubernetes.io/user: "{{ user }}"
spec:
  {% if image_pull_secret %}
  imagePullSecrets:
  - name: {{ image_pull_secret }}
  {% endif %}
  containers:
  - name: dask-scheduler-{{ user }}
    image: {{ image }}
    imagePullPolicy: {{ image_pull_policy }}
    livenessProbe:
      tcpSocket:
        port: 8786
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 8786
      initialDelaySeconds: 2
      periodSeconds: 5
  {% if not dev %}
    resources:
      limits:
        cpu: {{ shceduler_cpu }}
        memory: {{ scheduler_memory }}
      requests:
        cpu: {{ shceduler_cpu }}
        memory: {{ scheduler_memory }}
  {% endif %}
    command:
      - dask-scheduler 
      - --dashboard
      - --dashboard-prefix
      - /daskboard/{{ user }}
    ports:
    - containerPort: 8786
      protocol: TCP
    - containerPort: 8787
      protocol: TCP
