apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler-{{ user }}
spec:
  selector:
    component: dask-scheduler-{{ user }}
  ports:
  - protocol: TCP
    port: 8786
    name: scheduler
  - protocol: TCP
    port: 8787
    name: bokeh
